COURIER_ACTION_BURST = 0
COURIER_ACTION_ENEMY_SECRET_SHOP = 1
COURIER_ACTION_RETURN = 2
COURIER_ACTION_SECRET_SHOP = 3
COURIER_ACTION_SIDE_SHOP = 4
COURIER_ACTION_SIDE_SHOP2 = 5
COURIER_ACTION_TAKE_STASH_ITEMS = 6
COURIER_ACTION_TAKE_AND_TRANSFER_ITEMS = 7
COURIER_ACTION_TRANSFER_ITEMS = 8

COURIER_STATE_IDLE = 9
COURIER_STATE_AT_BASE = 10
COURIER_STATE_MOVING = 11
COURIER_STATE_DELIVERING_ITEMS = 12
COURIER_STATE_RETURNING_TO_BASE = 13
COURIER_STATE_DEAD = 14

-----------------------------------------

TEAM_RADIANT = 0
TEAM_DIRE = 1

LANE_TOP = 0
LANE_MID = 1
LANE_BOT = 2

-----------------------------------------

BOT_MODE_NONE = 0
BOT_MODE_LANING = 1
BOT_MODE_ATTACK = 2
BOT_MODE_ROAM = 3
BOT_MODE_RETREAT = 4
BOT_MODE_SECRET_SHOP = 5
BOT_MODE_SIDE_SHOP = 6
BOT_MODE_PUSH_TOWER_TOP = 7
BOT_MODE_PUSH_TOWER_MID = 8
BOT_MODE_PUSH_TOWER_BOT = 9
BOT_MODE_DEFEND_TOWER_TOP = 10
BOT_MODE_DEFEND_TOWER_MID = 11
BOT_MODE_DEFEND_TOWER_BOT = 12
BOT_MODE_ASSEMBLE = 13
BOT_MODE_TEAM_ROAM = 14
BOT_MODE_FARM = 15
BOT_MODE_DEFEND_ALLY = 16
BOT_MODE_EVASIVE_MANEUVERS = 17
BOT_MODE_ROSHAN = 18
BOT_MODE_ITEM = 19
BOT_MODE_WARD = 20

-----------------------------------------

SHOP_SIDE = 1
SHOP_SIDE2 = 2
