COURIER_ACTION_BURST = 0
COURIER_ACTION_ENEMY_SECRET_SHOP = 1
COURIER_ACTION_RETURN = 2
COURIER_ACTION_SECRET_SHOP = 3
COURIER_ACTION_SIDE_SHOP = 4
COURIER_ACTION_SIDE_SHOP2 = 5
COURIER_ACTION_TAKE_STASH_ITEMS = 6
COURIER_ACTION_TAKE_AND_TRANSFER_ITEMS = 7
COURIER_ACTION_TRANSFER_ITEMS = 8

COURIER_STATE_IDLE = 9
COURIER_STATE_AT_BASE = 10
COURIER_STATE_MOVING = 11
COURIER_STATE_DELIVERING_ITEMS = 12
COURIER_STATE_RETURNING_TO_BASE = 13
COURIER_STATE_DEAD = 14

-----------------------------------------

TEAM_RADIANT = 0
TEAM_DIRE = 1

LANE_TOP = 0
LANE_MID = 1
LANE_BOT = 2

-----------------------------------------
