local M = {}

M.INVENTORY_SIZE = 8
M.INVENTORY_AND_STASH_SIZE = 16

M.SHOP_USE_RADIUS = 250
M.BASE_SHOP_USE_RADIUS = 600

M.SHOP_WALK_RADIUS = 3000


M.ABILITY_NO_TARGET = 1
M.ABILITY_UNIT_TARGET = 2
M.ABILITY_LOCATION_TARGET = 3

return M
